use project_db;
SELECT * FROM customer_behaviour_analysis;

------------ Business Problem --------------

-- 1. Which category generates highest revenue?
SELECT 
	category,
	ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM customer_behaviour_analysis
GROUP BY category
ORDER BY highest_revenue DESC;

-- 2. Are discounts actually increasing purchase value?
SELECT * FROM customer_behaviour_analysis;

SELECT 
	discount_applied,
	ROUND(SUM(purchase_amount),2) AS total_revenue,
	ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_behaviour_analysis
GROUP BY discount_applied;

-- 3. What is the total revenue generated by male and female customer ? 
SELECT gender,round(sum(purchase_amount),2) as "Total_Revenue"
FROM customer_behaviour_analysis
group by gender;

-- 4. Which customer used a discount but still spent more then the average purchase amount ?
SELECT
	customer_id,
	purchase_amount,
	discount_applied
FROM customer_behaviour_analysis
WHERE discount_applied= 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behaviour_analysis)
order by purchase_amount desc 
limit 10;

-- 5. Which are the top 5 products with the highest average review rating. 
select item_purchased, round(avg(review_rating),2) as 'Average_Rating'
FROM customer_behaviour_analysis
group by item_purchased 
order by avg(review_rating)
limit 5;

-- 6. Average purchase: Standard vs Express shipping
SELECT 
	shipping_type,
	COUNT(DISTINCT customer_id) as order_placed,
	ROUND(AVG(purchase_amount),2)  as avg_purchase,
	ROUND(SUM(purchase_amount),2) AS revenue
FROM customer_behaviour_analysis
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
ORDER BY revenue DESC;

-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT 
	subscription_status,
	COUNT(customer_id) as users,
	ROUND(AVG(purchase_amount),2) as avg_revenue,
	ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- 8. What are the top 3 most purchased products within each category ?
WITH CTE AS 
(
SELECT 
	category,
	item_purchased,
	COUNT(item_purchased) AS most_purchased,
	RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM customer_behaviour_analysis
GROUP BY category,item_purchased
)
SELECT * FROM CTE
WHERE RNK <=3;

